### ISSUE TITLE
Check class implementation

### ISSUE THREAD

**Issue by Peter9192** [classmodel/class-web#16]
@Chiil please check the initial implementation of class in https://github.com/classmodel/class-web/blob/main/packages/class/src/class.ts

**Comment by Chiil** [comment]
All terms containing `wf` and capital `M` can be removed in the minimal CLASS implementation as shown here.

**Comment by Peter9192** [comment]
I assume that also includes `wqM`, and that `wf` (the calculated property) can be removed entirely for now.

**Comment by Chiil** [comment]
Yes, all related variables.
